
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec  4 2025 13:17:03 IST (Dec  4 2025 07:47:03 UTC)

// Verification Directory fv/fifo 

module fifo(clk, rst_n, wr_en, rd_en, din, dout, empty, full);
  input clk, rst_n, wr_en, rd_en;
  input [7:0] din;
  output [7:0] dout;
  output empty, full;
  wire clk, rst_n, wr_en, rd_en;
  wire [7:0] din;
  wire [7:0] dout;
  wire empty, full;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[3] ;
  wire [4:0] rd_ptr;
  wire [4:0] wr_ptr;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_54, n_55, n_56, n_57, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_199, n_200, n_201, n_202;
  assign full = 1'b0;
  DFFQX1 \dout_reg[0] (.CK (clk), .D (n_185), .Q (dout[0]));
  DFFQX1 \dout_reg[1] (.CK (clk), .D (n_184), .Q (dout[1]));
  DFFQX1 \dout_reg[3] (.CK (clk), .D (n_178), .Q (dout[3]));
  DFFQX1 \dout_reg[4] (.CK (clk), .D (n_183), .Q (dout[4]));
  DFFQX1 \dout_reg[5] (.CK (clk), .D (n_182), .Q (dout[5]));
  DFFQX1 \dout_reg[2] (.CK (clk), .D (n_181), .Q (dout[2]));
  DFFQX1 \dout_reg[6] (.CK (clk), .D (n_180), .Q (dout[6]));
  DFFQX1 \dout_reg[7] (.CK (clk), .D (n_179), .Q (dout[7]));
  INVXL g5776(.A (n_172), .Y (n_185));
  INVXL g5778(.A (n_177), .Y (n_184));
  INVXL g5777(.A (n_174), .Y (n_183));
  INVXL g5779(.A (n_171), .Y (n_182));
  INVXL g5786(.A (n_173), .Y (n_181));
  INVXL g5785(.A (n_176), .Y (n_180));
  INVXL g5784(.A (n_169), .Y (n_179));
  INVXL g5787(.A (n_170), .Y (n_178));
  AOI211XL g5782__2398(.A0 (\mem[15] [1]), .A1 (n_175), .B0 (n_156),
       .C0 (n_161), .Y (n_177));
  AOI211XL g5789__5107(.A0 (\mem[15] [6]), .A1 (n_175), .B0 (n_160),
       .C0 (n_168), .Y (n_176));
  AOI211XL g5781__6260(.A0 (\mem[15] [4]), .A1 (n_175), .B0 (n_162),
       .C0 (n_155), .Y (n_174));
  AOI211XL g5790__4319(.A0 (\mem[15] [2]), .A1 (n_175), .B0 (n_158),
       .C0 (n_167), .Y (n_173));
  AOI211XL g5780__8428(.A0 (\mem[15] [0]), .A1 (n_175), .B0 (n_165),
       .C0 (n_157), .Y (n_172));
  AOI211XL g5783__5526(.A0 (\mem[15] [5]), .A1 (n_175), .B0 (n_153),
       .C0 (n_166), .Y (n_171));
  AOI211XL g5791__6783(.A0 (\mem[15] [3]), .A1 (n_175), .B0 (n_154),
       .C0 (n_164), .Y (n_170));
  AOI211XL g5788__3680(.A0 (\mem[15] [7]), .A1 (n_175), .B0 (n_159),
       .C0 (n_163), .Y (n_169));
  NAND4XL g5803__1617(.A (n_149), .B (n_128), .C (n_151), .D (n_150),
       .Y (n_168));
  NAND4XL g5801__2802(.A (n_145), .B (n_148), .C (n_138), .D (n_134),
       .Y (n_167));
  NAND4XL g5798__1705(.A (n_139), .B (n_121), .C (n_120), .D (n_119),
       .Y (n_166));
  NAND4XL g5804__5122(.A (n_113), .B (n_117), .C (n_142), .D (n_132),
       .Y (n_165));
  NAND4XL g5793__8246(.A (n_114), .B (n_116), .C (n_115), .D (n_129),
       .Y (n_164));
  NAND4XL g5806__7098(.A (n_133), .B (n_137), .C (n_131), .D (n_152),
       .Y (n_163));
  NAND4XL g5792__6131(.A (n_127), .B (n_130), .C (n_126), .D (n_125),
       .Y (n_162));
  NAND4XL g5795__1881(.A (n_122), .B (n_118), .C (n_124), .D (n_123),
       .Y (n_161));
  NAND4XL g5802__5115(.A (n_74), .B (n_78), .C (n_80), .D (n_76), .Y
       (n_160));
  NAND4XL g5800__7482(.A (n_105), .B (n_101), .C (n_81), .D (n_106), .Y
       (n_159));
  NAND4XL g5799__4733(.A (n_79), .B (n_88), .C (n_112), .D (n_77), .Y
       (n_158));
  NAND4XL g5805__6161(.A (n_87), .B (n_91), .C (n_75), .D (n_82), .Y
       (n_157));
  NAND4XL g5796__9315(.A (n_107), .B (n_93), .C (n_89), .D (n_111), .Y
       (n_156));
  NAND4XL g5794__9945(.A (n_100), .B (n_102), .C (n_110), .D (n_97), .Y
       (n_155));
  NAND4XL g5807__2883(.A (n_94), .B (n_73), .C (n_92), .D (n_90), .Y
       (n_154));
  NAND4XL g5797__2346(.A (n_84), .B (n_83), .C (n_86), .D (n_85), .Y
       (n_153));
  AOI22XL g5876__1666(.A0 (n_141), .A1 (\mem[12] [7]), .B0 (n_140), .B1
       (\mem[11] [7]), .Y (n_152));
  AOI22XL g5859__7410(.A0 (n_136), .A1 (\mem[8] [6]), .B0 (n_135), .B1
       (\mem[7] [6]), .Y (n_151));
  AOI22XL g5860__6417(.A0 (n_147), .A1 (\mem[13] [6]), .B0 (n_146), .B1
       (\mem[14] [6]), .Y (n_150));
  AOI22XL g5861__5477(.A0 (n_144), .A1 (\mem[9] [6]), .B0 (n_143), .B1
       (\mem[10] [6]), .Y (n_149));
  AOI22XL g5862__2398(.A0 (n_147), .A1 (\mem[13] [2]), .B0 (n_146), .B1
       (\mem[14] [2]), .Y (n_148));
  AOI22XL g5863__5107(.A0 (n_144), .A1 (\mem[9] [2]), .B0 (n_143), .B1
       (\mem[10] [2]), .Y (n_145));
  AOI22XL g5864__6260(.A0 (n_141), .A1 (\mem[12] [0]), .B0 (n_140), .B1
       (\mem[11] [0]), .Y (n_142));
  AOI22XL g5865__4319(.A0 (n_144), .A1 (\mem[9] [5]), .B0 (n_143), .B1
       (\mem[10] [5]), .Y (n_139));
  AOI22XL g5866__8428(.A0 (n_141), .A1 (\mem[12] [2]), .B0 (n_140), .B1
       (\mem[11] [2]), .Y (n_138));
  AOI22XL g5870__5526(.A0 (n_136), .A1 (\mem[8] [7]), .B0 (n_135), .B1
       (\mem[7] [7]), .Y (n_137));
  AOI22XL g5871__6783(.A0 (n_136), .A1 (\mem[8] [2]), .B0 (n_135), .B1
       (\mem[7] [2]), .Y (n_134));
  AOI22XL g5872__3680(.A0 (n_144), .A1 (\mem[9] [7]), .B0 (n_143), .B1
       (\mem[10] [7]), .Y (n_133));
  AOI22XL g5873__1617(.A0 (n_147), .A1 (\mem[13] [0]), .B0 (n_146), .B1
       (\mem[14] [0]), .Y (n_132));
  AOI22XL g5874__2802(.A0 (n_147), .A1 (\mem[13] [7]), .B0 (n_146), .B1
       (\mem[14] [7]), .Y (n_131));
  AOI22XL g5830__1705(.A0 (n_147), .A1 (\mem[13] [4]), .B0 (n_146), .B1
       (\mem[14] [4]), .Y (n_130));
  AOI22XL g5822__5122(.A0 (n_136), .A1 (\mem[8] [3]), .B0 (n_135), .B1
       (\mem[7] [3]), .Y (n_129));
  AOI22XL g5857__8246(.A0 (n_141), .A1 (\mem[12] [6]), .B0 (n_140), .B1
       (\mem[11] [6]), .Y (n_128));
  AOI22XL g5832__7098(.A0 (n_144), .A1 (\mem[9] [4]), .B0 (n_143), .B1
       (\mem[10] [4]), .Y (n_127));
  AOI22XL g5834__6131(.A0 (n_141), .A1 (\mem[12] [4]), .B0 (n_140), .B1
       (\mem[11] [4]), .Y (n_126));
  AOI22XL g5835__1881(.A0 (n_136), .A1 (\mem[8] [4]), .B0 (n_135), .B1
       (\mem[7] [4]), .Y (n_125));
  AOI22XL g5837__5115(.A0 (n_147), .A1 (\mem[13] [1]), .B0 (n_146), .B1
       (\mem[14] [1]), .Y (n_124));
  AOI22XL g5839__7482(.A0 (n_141), .A1 (\mem[12] [1]), .B0 (n_140), .B1
       (\mem[11] [1]), .Y (n_123));
  AOI22XL g5841__4733(.A0 (n_144), .A1 (\mem[9] [1]), .B0 (n_143), .B1
       (\mem[10] [1]), .Y (n_122));
  AOI22XL g5844__6161(.A0 (n_141), .A1 (\mem[12] [5]), .B0 (n_140), .B1
       (\mem[11] [5]), .Y (n_121));
  AOI22XL g5846__9315(.A0 (n_136), .A1 (\mem[8] [5]), .B0 (n_135), .B1
       (\mem[7] [5]), .Y (n_120));
  AOI22XL g5847__9945(.A0 (n_147), .A1 (\mem[13] [5]), .B0 (n_146), .B1
       (\mem[14] [5]), .Y (n_119));
  AOI22XL g5817__2883(.A0 (n_136), .A1 (\mem[8] [1]), .B0 (n_135), .B1
       (\mem[7] [1]), .Y (n_118));
  AOI22XL g5850__2346(.A0 (n_136), .A1 (\mem[8] [0]), .B0 (n_135), .B1
       (\mem[7] [0]), .Y (n_117));
  AOI22XL g5818__1666(.A0 (n_141), .A1 (\mem[12] [3]), .B0 (n_140), .B1
       (\mem[11] [3]), .Y (n_116));
  AOI22XL g5819__7410(.A0 (n_147), .A1 (\mem[13] [3]), .B0 (n_146), .B1
       (\mem[14] [3]), .Y (n_115));
  AOI22XL g5821__6417(.A0 (n_144), .A1 (\mem[9] [3]), .B0 (n_143), .B1
       (\mem[10] [3]), .Y (n_114));
  AOI22XL g5877__5477(.A0 (n_144), .A1 (\mem[9] [0]), .B0 (n_143), .B1
       (\mem[10] [0]), .Y (n_113));
  AOI22XL g5833__2398(.A0 (n_96), .A1 (\mem[1] [2]), .B0 (n_95), .B1
       (\mem[2] [2]), .Y (n_112));
  AOI22XL g5824__5107(.A0 (n_109), .A1 (\mem[0] [1]), .B0 (n_108), .B1
       (dout[1]), .Y (n_111));
  AOI22XL g5825__6260(.A0 (n_109), .A1 (\mem[0] [4]), .B0 (n_108), .B1
       (dout[4]), .Y (n_110));
  AOI22XL g5826__4319(.A0 (n_104), .A1 (\mem[5] [1]), .B0 (n_103), .B1
       (\mem[6] [1]), .Y (n_107));
  AOI22XL g5867__8428(.A0 (n_109), .A1 (\mem[0] [7]), .B0 (n_108), .B1
       (dout[7]), .Y (n_106));
  AOI22XL g5868__5526(.A0 (n_104), .A1 (\mem[5] [7]), .B0 (n_103), .B1
       (\mem[6] [7]), .Y (n_105));
  AOI22XL g5827__6783(.A0 (n_104), .A1 (\mem[5] [4]), .B0 (n_103), .B1
       (\mem[6] [4]), .Y (n_102));
  AOI22XL g5869__3680(.A0 (n_99), .A1 (\mem[4] [7]), .B0 (n_98), .B1
       (\mem[3] [7]), .Y (n_101));
  AOI22XL g5828__1617(.A0 (n_99), .A1 (\mem[4] [4]), .B0 (n_98), .B1
       (\mem[3] [4]), .Y (n_100));
  AOI22XL g5829__2802(.A0 (n_96), .A1 (\mem[1] [4]), .B0 (n_95), .B1
       (\mem[2] [4]), .Y (n_97));
  AOI22XL g5875__1705(.A0 (n_104), .A1 (\mem[5] [3]), .B0 (n_103), .B1
       (\mem[6] [3]), .Y (n_94));
  AOI22XL g5831__5122(.A0 (n_99), .A1 (\mem[4] [1]), .B0 (n_98), .B1
       (\mem[3] [1]), .Y (n_93));
  AOI22XL g5878__8246(.A0 (n_96), .A1 (\mem[1] [3]), .B0 (n_95), .B1
       (\mem[2] [3]), .Y (n_92));
  AOI22XL g5879__7098(.A0 (n_104), .A1 (\mem[5] [0]), .B0 (n_103), .B1
       (\mem[6] [0]), .Y (n_91));
  AOI22XL g5880__6131(.A0 (n_109), .A1 (\mem[0] [3]), .B0 (n_108), .B1
       (dout[3]), .Y (n_90));
  AOI22XL g5823__1881(.A0 (n_96), .A1 (\mem[1] [1]), .B0 (n_95), .B1
       (\mem[2] [1]), .Y (n_89));
  AOI22XL g5858__5115(.A0 (n_99), .A1 (\mem[4] [2]), .B0 (n_98), .B1
       (\mem[3] [2]), .Y (n_88));
  AOI22XL g5836__7482(.A0 (n_99), .A1 (\mem[4] [0]), .B0 (n_98), .B1
       (\mem[3] [0]), .Y (n_87));
  AOI22XL g5838__4733(.A0 (n_109), .A1 (\mem[0] [5]), .B0 (n_108), .B1
       (dout[5]), .Y (n_86));
  AOI22XL g5840__6161(.A0 (n_96), .A1 (\mem[1] [5]), .B0 (n_95), .B1
       (\mem[2] [5]), .Y (n_85));
  AOI22XL g5842__9315(.A0 (n_104), .A1 (\mem[5] [5]), .B0 (n_103), .B1
       (\mem[6] [5]), .Y (n_84));
  AOI22XL g5843__9945(.A0 (n_99), .A1 (\mem[4] [5]), .B0 (n_98), .B1
       (\mem[3] [5]), .Y (n_83));
  AOI22XL g5845__2883(.A0 (n_96), .A1 (\mem[1] [0]), .B0 (n_95), .B1
       (\mem[2] [0]), .Y (n_82));
  AOI22XL g5849__2346(.A0 (n_96), .A1 (\mem[1] [7]), .B0 (n_95), .B1
       (\mem[2] [7]), .Y (n_81));
  AOI22XL g5851__1666(.A0 (n_96), .A1 (\mem[1] [6]), .B0 (n_95), .B1
       (\mem[2] [6]), .Y (n_80));
  AOI22XL g5852__7410(.A0 (n_104), .A1 (\mem[5] [2]), .B0 (n_103), .B1
       (\mem[6] [2]), .Y (n_79));
  AOI22XL g5853__6417(.A0 (n_99), .A1 (\mem[4] [6]), .B0 (n_98), .B1
       (\mem[3] [6]), .Y (n_78));
  AOI22XL g5854__5477(.A0 (n_109), .A1 (\mem[0] [2]), .B0 (n_108), .B1
       (dout[2]), .Y (n_77));
  AOI22XL g5855__2398(.A0 (n_109), .A1 (\mem[0] [6]), .B0 (n_108), .B1
       (dout[6]), .Y (n_76));
  AOI22XL g5820__5107(.A0 (n_109), .A1 (\mem[0] [0]), .B0 (n_108), .B1
       (dout[0]), .Y (n_75));
  AOI22XL g5856__6260(.A0 (n_104), .A1 (\mem[5] [6]), .B0 (n_103), .B1
       (\mem[6] [6]), .Y (n_74));
  AOI22XL g5881__4319(.A0 (n_99), .A1 (\mem[4] [3]), .B0 (n_98), .B1
       (\mem[3] [3]), .Y (n_73));
  NOR2BX1 g5897__8428(.AN (n_71), .B (n_72), .Y (n_143));
  NOR2XL g5896__5526(.A (n_70), .B (n_72), .Y (n_175));
  NOR2BX1 g5893__6783(.AN (n_71), .B (n_69), .Y (n_136));
  NOR2XL g5902__3680(.A (n_70), .B (n_69), .Y (n_147));
  NOR2XL g5907__1617(.A (n_68), .B (n_69), .Y (n_144));
  NOR2XL g5906__2802(.A (n_68), .B (n_72), .Y (n_140));
  NOR2XL g5905__1705(.A (n_67), .B (n_72), .Y (n_146));
  NOR2XL g5912__5122(.A (n_67), .B (n_69), .Y (n_141));
  NOR2BX1 g5903__8246(.AN (n_66), .B (n_70), .Y (n_104));
  AND2X1 g5898__7098(.A (n_71), .B (n_65), .Y (n_95));
  AND2X1 g5895__6131(.A (n_71), .B (n_66), .Y (n_109));
  NOR2BX1 g5904__1881(.AN (n_66), .B (n_67), .Y (n_99));
  AND2X1 g5910__5115(.A (n_64), .B (n_65), .Y (n_98));
  NOR2BX1 g5909__7482(.AN (n_65), .B (n_70), .Y (n_135));
  AND2X1 g5908__4733(.A (n_64), .B (n_66), .Y (n_96));
  NOR2BX1 g5911__6161(.AN (n_65), .B (n_67), .Y (n_103));
  NAND3X1 g5916__9315(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_63), .Y
       (n_72));
  NAND3X1 g5918__9945(.A (rd_ptr[3]), .B (n_62), .C (n_63), .Y (n_69));
  NOR3X1 g5914__2883(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_108), .Y
       (n_66));
  NOR3X1 g5917__2346(.A (rd_ptr[3]), .B (n_62), .C (n_108), .Y (n_65));
  SDFFRHQX1 \rd_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (n_60), .SI
       (n_61), .SE (rd_ptr[0]), .Q (rd_ptr[0]));
  CLKINVX1 g5928(.A (n_108), .Y (n_63));
  SDFFRHQX1 \rd_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (n_32), .SI
       (rd_ptr[3]), .SE (n_61), .Q (rd_ptr[3]));
  SDFFRHQX1 \rd_ptr_reg[4] (.RN (rst_n), .CK (clk), .D (n_41), .SI
       (rd_ptr[4]), .SE (n_61), .Q (rd_ptr[4]));
  SDFFRHQX1 \rd_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (n_24), .SI
       (rd_ptr[2]), .SE (n_61), .Q (rd_ptr[2]));
  SDFFRHQX1 \rd_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_5), .SI
       (rd_ptr[1]), .SE (n_61), .Q (rd_ptr[1]));
  NAND2XL g5937__1666(.A (rst_n), .B (n_60), .Y (n_108));
  SDFFRHQX1 \wr_ptr_reg[4] (.RN (rst_n), .CK (clk), .D (wr_ptr[4]), .SI
       (n_44), .SE (wr_en), .Q (wr_ptr[4]));
  SDFFQX1 \mem_reg[2][1] (.CK (clk), .D (din[1]), .SI (\mem[2] [1]),
       .SE (n_200), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[0][7] (.CK (clk), .D (din[7]), .SI (\mem[0] [7]),
       .SE (n_199), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[0][2] (.CK (clk), .D (din[2]), .SI (\mem[0] [2]),
       .SE (n_199), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[2][0] (.CK (clk), .D (din[0]), .SI (\mem[2] [0]),
       .SE (n_200), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][2] (.CK (clk), .D (din[2]), .SI (\mem[2] [2]),
       .SE (n_200), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (clk), .D (din[3]), .SI (\mem[2] [3]),
       .SE (n_200), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][4] (.CK (clk), .D (din[4]), .SI (\mem[2] [4]),
       .SE (n_200), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (clk), .D (din[5]), .SI (\mem[2] [5]),
       .SE (n_200), .Q (\mem[2] [5]));
  CLKINVX1 g5988(.A (n_61), .Y (n_60));
  SDFFQX1 \mem_reg[2][7] (.CK (clk), .D (din[7]), .SI (\mem[2] [7]),
       .SE (n_200), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[0][6] (.CK (clk), .D (din[6]), .SI (\mem[0] [6]),
       .SE (n_199), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][4] (.CK (clk), .D (din[4]), .SI (\mem[0] [4]),
       .SE (n_199), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][0] (.CK (clk), .D (din[0]), .SI (\mem[0] [0]),
       .SE (n_199), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][1] (.CK (clk), .D (din[1]), .SI (\mem[0] [1]),
       .SE (n_199), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][3] (.CK (clk), .D (din[3]), .SI (\mem[0] [3]),
       .SE (n_199), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][5] (.CK (clk), .D (din[5]), .SI (\mem[0] [5]),
       .SE (n_199), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (clk), .D (din[6]), .SI (\mem[2] [6]),
       .SE (n_200), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[5][5] (.CK (clk), .D (\mem[5] [5]), .SI (din[5]),
       .SE (n_56), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (clk), .D (\mem[8] [6]), .SI (din[6]),
       .SE (n_57), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[10][6] (.CK (clk), .D (din[6]), .SI (\mem[10] [6]),
       .SE (n_48), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[8][7] (.CK (clk), .D (\mem[8] [7]), .SI (din[7]),
       .SE (n_57), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[8][5] (.CK (clk), .D (\mem[8] [5]), .SI (din[5]),
       .SE (n_57), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[1][6] (.CK (clk), .D (\mem[1] [6]), .SI (din[6]),
       .SE (n_50), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[5][7] (.CK (clk), .D (\mem[5] [7]), .SI (din[7]),
       .SE (n_56), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[8][2] (.CK (clk), .D (\mem[8] [2]), .SI (din[2]),
       .SE (n_57), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (clk), .D (\mem[4] [3]), .SI (din[3]),
       .SE (n_55), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[14][5] (.CK (clk), .D (\mem[14] [5]), .SI (din[5]),
       .SE (n_54), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[5][3] (.CK (clk), .D (\mem[5] [3]), .SI (din[3]),
       .SE (n_56), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[13][6] (.CK (clk), .D (\mem[13] [6]), .SI (din[6]),
       .SE (n_51), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[6][7] (.CK (clk), .D (din[7]), .SI (\mem[6] [7]),
       .SE (n_47), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[9][6] (.CK (clk), .D (\mem[9] [6]), .SI (din[6]),
       .SE (n_46), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[4][7] (.CK (clk), .D (\mem[4] [7]), .SI (din[7]),
       .SE (n_55), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[7][6] (.CK (clk), .D (\mem[7] [6]), .SI (din[6]),
       .SE (n_201), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[14][6] (.CK (clk), .D (\mem[14] [6]), .SI (din[6]),
       .SE (n_54), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[14][4] (.CK (clk), .D (\mem[14] [4]), .SI (din[4]),
       .SE (n_54), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[12][6] (.CK (clk), .D (\mem[12] [6]), .SI (din[6]),
       .SE (n_45), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[15][1] (.CK (clk), .D (\mem[15] [1]), .SI (din[1]),
       .SE (n_52), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[7][3] (.CK (clk), .D (\mem[7] [3]), .SI (din[3]),
       .SE (n_201), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[15][0] (.CK (clk), .D (\mem[15] [0]), .SI (din[0]),
       .SE (n_52), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][7] (.CK (clk), .D (\mem[15] [7]), .SI (din[7]),
       .SE (n_52), .Q (\mem[15] [7]));
  SDFFQX1 \mem_reg[15][2] (.CK (clk), .D (\mem[15] [2]), .SI (din[2]),
       .SE (n_52), .Q (\mem[15] [2]));
  SDFFQX1 \mem_reg[15][4] (.CK (clk), .D (\mem[15] [4]), .SI (din[4]),
       .SE (n_52), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][3] (.CK (clk), .D (\mem[15] [3]), .SI (din[3]),
       .SE (n_52), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][6] (.CK (clk), .D (\mem[15] [6]), .SI (din[6]),
       .SE (n_52), .Q (\mem[15] [6]));
  SDFFQX1 \mem_reg[7][2] (.CK (clk), .D (\mem[7] [2]), .SI (din[2]),
       .SE (n_201), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][1] (.CK (clk), .D (\mem[7] [1]), .SI (din[1]),
       .SE (n_201), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][0] (.CK (clk), .D (\mem[7] [0]), .SI (din[0]),
       .SE (n_201), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][5] (.CK (clk), .D (\mem[7] [5]), .SI (din[5]),
       .SE (n_201), .Q (\mem[7] [5]));
  SDFFQX1 \mem_reg[7][4] (.CK (clk), .D (\mem[7] [4]), .SI (din[4]),
       .SE (n_201), .Q (\mem[7] [4]));
  SDFFQX1 \mem_reg[7][7] (.CK (clk), .D (\mem[7] [7]), .SI (din[7]),
       .SE (n_201), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[13][4] (.CK (clk), .D (\mem[13] [4]), .SI (din[4]),
       .SE (n_51), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[1][2] (.CK (clk), .D (\mem[1] [2]), .SI (din[2]),
       .SE (n_50), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[1][3] (.CK (clk), .D (\mem[1] [3]), .SI (din[3]),
       .SE (n_50), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[1][4] (.CK (clk), .D (\mem[1] [4]), .SI (din[4]),
       .SE (n_50), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[1][7] (.CK (clk), .D (\mem[1] [7]), .SI (din[7]),
       .SE (n_50), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[4][0] (.CK (clk), .D (\mem[4] [0]), .SI (din[0]),
       .SE (n_55), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (clk), .D (\mem[4] [1]), .SI (din[1]),
       .SE (n_55), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (clk), .D (\mem[4] [2]), .SI (din[2]),
       .SE (n_55), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][4] (.CK (clk), .D (\mem[4] [4]), .SI (din[4]),
       .SE (n_55), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[4][5] (.CK (clk), .D (\mem[4] [5]), .SI (din[5]),
       .SE (n_55), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (clk), .D (\mem[4] [6]), .SI (din[6]),
       .SE (n_55), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[5][0] (.CK (clk), .D (\mem[5] [0]), .SI (din[0]),
       .SE (n_56), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (clk), .D (\mem[5] [1]), .SI (din[1]),
       .SE (n_56), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[5][2] (.CK (clk), .D (\mem[5] [2]), .SI (din[2]),
       .SE (n_56), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[5][4] (.CK (clk), .D (\mem[5] [4]), .SI (din[4]),
       .SE (n_56), .Q (\mem[5] [4]));
  NAND2BX1 g6038__7410(.AN (n_49), .B (rd_en), .Y (n_61));
  SDFFQX1 \mem_reg[10][2] (.CK (clk), .D (din[2]), .SI (\mem[10] [2]),
       .SE (n_48), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[6][0] (.CK (clk), .D (din[0]), .SI (\mem[6] [0]),
       .SE (n_47), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][1] (.CK (clk), .D (din[1]), .SI (\mem[6] [1]),
       .SE (n_47), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][2] (.CK (clk), .D (din[2]), .SI (\mem[6] [2]),
       .SE (n_47), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[6][4] (.CK (clk), .D (din[4]), .SI (\mem[6] [4]),
       .SE (n_47), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (clk), .D (din[5]), .SI (\mem[6] [5]),
       .SE (n_47), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (clk), .D (din[6]), .SI (\mem[6] [6]),
       .SE (n_47), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[8][0] (.CK (clk), .D (\mem[8] [0]), .SI (din[0]),
       .SE (n_57), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][1] (.CK (clk), .D (\mem[8] [1]), .SI (din[1]),
       .SE (n_57), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[1][5] (.CK (clk), .D (\mem[1] [5]), .SI (din[5]),
       .SE (n_50), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[8][4] (.CK (clk), .D (\mem[8] [4]), .SI (din[4]),
       .SE (n_57), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][3] (.CK (clk), .D (\mem[8] [3]), .SI (din[3]),
       .SE (n_57), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[9][0] (.CK (clk), .D (\mem[9] [0]), .SI (din[0]),
       .SE (n_46), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (clk), .D (\mem[9] [1]), .SI (din[1]),
       .SE (n_46), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][2] (.CK (clk), .D (\mem[9] [2]), .SI (din[2]),
       .SE (n_46), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[9][3] (.CK (clk), .D (\mem[9] [3]), .SI (din[3]),
       .SE (n_46), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[1][1] (.CK (clk), .D (\mem[1] [1]), .SI (din[1]),
       .SE (n_50), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[9][4] (.CK (clk), .D (\mem[9] [4]), .SI (din[4]),
       .SE (n_46), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][5] (.CK (clk), .D (\mem[9] [5]), .SI (din[5]),
       .SE (n_46), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[9][7] (.CK (clk), .D (\mem[9] [7]), .SI (din[7]),
       .SE (n_46), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[10][0] (.CK (clk), .D (din[0]), .SI (\mem[10] [0]),
       .SE (n_48), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[10][1] (.CK (clk), .D (din[1]), .SI (\mem[10] [1]),
       .SE (n_48), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[10][3] (.CK (clk), .D (din[3]), .SI (\mem[10] [3]),
       .SE (n_48), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][4] (.CK (clk), .D (din[4]), .SI (\mem[10] [4]),
       .SE (n_48), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[10][5] (.CK (clk), .D (din[5]), .SI (\mem[10] [5]),
       .SE (n_48), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[10][7] (.CK (clk), .D (din[7]), .SI (\mem[10] [7]),
       .SE (n_48), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[12][0] (.CK (clk), .D (\mem[12] [0]), .SI (din[0]),
       .SE (n_45), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (clk), .D (\mem[12] [1]), .SI (din[1]),
       .SE (n_45), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][3] (.CK (clk), .D (\mem[12] [3]), .SI (din[3]),
       .SE (n_45), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (clk), .D (\mem[12] [4]), .SI (din[4]),
       .SE (n_45), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][5] (.CK (clk), .D (\mem[12] [5]), .SI (din[5]),
       .SE (n_45), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][7] (.CK (clk), .D (\mem[12] [7]), .SI (din[7]),
       .SE (n_45), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[13][0] (.CK (clk), .D (\mem[13] [0]), .SI (din[0]),
       .SE (n_51), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][1] (.CK (clk), .D (\mem[13] [1]), .SI (din[1]),
       .SE (n_51), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[13][3] (.CK (clk), .D (\mem[13] [3]), .SI (din[3]),
       .SE (n_51), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[13][5] (.CK (clk), .D (\mem[13] [5]), .SI (din[5]),
       .SE (n_51), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[14][0] (.CK (clk), .D (\mem[14] [0]), .SI (din[0]),
       .SE (n_54), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[13][7] (.CK (clk), .D (\mem[13] [7]), .SI (din[7]),
       .SE (n_51), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[14][3] (.CK (clk), .D (\mem[14] [3]), .SI (din[3]),
       .SE (n_54), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][2] (.CK (clk), .D (\mem[14] [2]), .SI (din[2]),
       .SE (n_54), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[15][5] (.CK (clk), .D (\mem[15] [5]), .SI (din[5]),
       .SE (n_52), .Q (\mem[15] [5]));
  SDFFQX1 \mem_reg[12][2] (.CK (clk), .D (\mem[12] [2]), .SI (din[2]),
       .SE (n_45), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[14][7] (.CK (clk), .D (\mem[14] [7]), .SI (din[7]),
       .SE (n_54), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[1][0] (.CK (clk), .D (\mem[1] [0]), .SI (din[0]),
       .SE (n_50), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[6][3] (.CK (clk), .D (din[3]), .SI (\mem[6] [3]),
       .SE (n_47), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[14][1] (.CK (clk), .D (\mem[14] [1]), .SI (din[1]),
       .SE (n_54), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[5][6] (.CK (clk), .D (\mem[5] [6]), .SI (din[6]),
       .SE (n_56), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[13][2] (.CK (clk), .D (\mem[13] [2]), .SI (din[2]),
       .SE (n_51), .Q (\mem[13] [2]));
  SDFFRHQX1 \wr_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (wr_ptr[3]), .SI
       (n_37), .SE (wr_en), .Q (wr_ptr[3]));
  OAI21X1 g5886__6417(.A0 (wr_ptr[4]), .A1 (n_36), .B0 (n_33), .Y
       (n_44));
  SDFFQX1 \mem_reg[11][7] (.CK (clk), .D (\mem[11] [7]), .SI (din[7]),
       .SE (n_43), .Q (\mem[11] [7]));
  NOR3X1 g6042__5477(.A (n_10), .B (n_12), .C (n_25), .Y (n_49));
  SDFFQX1 \mem_reg[11][0] (.CK (clk), .D (\mem[11] [0]), .SI (din[0]),
       .SE (n_43), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][3] (.CK (clk), .D (\mem[11] [3]), .SI (din[3]),
       .SE (n_43), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[11][5] (.CK (clk), .D (\mem[11] [5]), .SI (din[5]),
       .SE (n_43), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[11][1] (.CK (clk), .D (\mem[11] [1]), .SI (din[1]),
       .SE (n_43), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[3][1] (.CK (clk), .D (din[1]), .SI (\mem[3] [1]),
       .SE (n_202), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][5] (.CK (clk), .D (din[5]), .SI (\mem[3] [5]),
       .SE (n_202), .Q (\mem[3] [5]));
  SDFFRHQX1 \wr_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (wr_ptr[2]), .SI
       (n_21), .SE (wr_en), .Q (wr_ptr[2]));
  OAI21X1 g5989__2398(.A0 (rd_ptr[4]), .A1 (n_38), .B0 (n_39), .Y
       (n_41));
  SDFFQX1 \mem_reg[3][2] (.CK (clk), .D (din[2]), .SI (\mem[3] [2]),
       .SE (n_202), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][3] (.CK (clk), .D (din[3]), .SI (\mem[3] [3]),
       .SE (n_202), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[3][4] (.CK (clk), .D (din[4]), .SI (\mem[3] [4]),
       .SE (n_202), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][6] (.CK (clk), .D (din[6]), .SI (\mem[3] [6]),
       .SE (n_202), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][7] (.CK (clk), .D (din[7]), .SI (\mem[3] [7]),
       .SE (n_202), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[3][0] (.CK (clk), .D (din[0]), .SI (\mem[3] [0]),
       .SE (n_202), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[11][2] (.CK (clk), .D (\mem[11] [2]), .SI (din[2]),
       .SE (n_43), .Q (\mem[11] [2]));
  SDFFQX1 \mem_reg[11][4] (.CK (clk), .D (\mem[11] [4]), .SI (din[4]),
       .SE (n_43), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[11][6] (.CK (clk), .D (\mem[11] [6]), .SI (din[6]),
       .SE (n_43), .Q (\mem[11] [6]));
  NAND2XL g6041__4319(.A (rd_ptr[4]), .B (n_38), .Y (n_39));
  OA21XL g5929__8428(.A0 (wr_ptr[3]), .A1 (n_20), .B0 (n_36), .Y
       (n_37));
  NOR2XL g6047__5526(.A (n_31), .B (n_35), .Y (n_56));
  NOR2XL g6050__6783(.A (n_34), .B (n_35), .Y (n_51));
  NOR2BX1 g6051__1617(.AN (n_40), .B (n_35), .Y (n_50));
  NOR2XL g6052__2802(.A (n_27), .B (n_35), .Y (n_46));
  NOR2XL g6054__1705(.A (n_34), .B (n_30), .Y (n_54));
  NAND2XL g5891__5122(.A (wr_ptr[4]), .B (n_36), .Y (n_33));
  OA21XL g6058__8246(.A0 (rd_ptr[3]), .A1 (n_18), .B0 (n_38), .Y
       (n_32));
  NOR2XL g6062__7098(.A (n_31), .B (n_28), .Y (n_55));
  OR2X1 g6061__6131(.A (n_31), .B (n_30), .Y (n_47));
  NOR2XL g5913__1881(.A (n_36), .B (n_29), .Y (n_52));
  NOR2XL g6049__5115(.A (n_34), .B (n_28), .Y (n_45));
  NOR2XL g6063__7482(.A (n_27), .B (n_28), .Y (n_57));
  OR2X1 g6060__4733(.A (n_27), .B (n_30), .Y (n_48));
  OAI21X1 g6043__6161(.A0 (n_11), .A1 (wr_en), .B0 (n_13), .Y (n_26));
  OAI211X1 g6055__9315(.A0 (wr_ptr[1]), .A1 (n_62), .B0 (n_8), .C0
       (n_6), .Y (n_25));
  OAI221X1 g6057__9945(.A0 (n_62), .A1 (n_68), .B0 (n_7), .B1
       (rd_ptr[1]), .C0 (n_67), .Y (n_24));
  AOI21X1 g6045__2883(.A0 (n_9), .A1 (n_19), .B0 (n_20), .Y (n_21));
  NAND2XL g6037__2346(.A (wr_ptr[3]), .B (n_20), .Y (n_36));
  NOR3X1 g6044__1666(.A (n_19), .B (n_27), .C (n_29), .Y (n_43));
  NAND2XL g6071__6417(.A (rd_ptr[3]), .B (n_18), .Y (n_38));
  NAND2XL g6066__5477(.A (wr_ptr[0]), .B (n_15), .Y (n_35));
  NAND3X1 g6072__2398(.A (wr_ptr[1]), .B (n_16), .C (n_17), .Y (n_30));
  NAND2XL g6067__5107(.A (n_16), .B (n_15), .Y (n_28));
  SDFFRHQX1 \wr_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (wr_en), .SI
       (n_0), .SE (wr_ptr[0]), .Q (wr_ptr[0]));
  OAI211X1 g6056__6260(.A0 (wr_ptr[0]), .A1 (wr_ptr[1]), .B0 (n_19),
       .C0 (wr_en), .Y (n_13));
  OAI222XL g6070__4319(.A0 (rd_ptr[1]), .A1 (n_11), .B0 (wr_ptr[0]),
       .B1 (n_4), .C0 (n_16), .C1 (rd_ptr[0]), .Y (n_12));
  AOI21XL g6073__8428(.A0 (rd_ptr[4]), .A1 (wr_ptr[4]), .B0 (n_1), .Y
       (n_10));
  NOR2XL g6074__5526(.A (n_62), .B (n_70), .Y (n_18));
  NOR2XL g6075__6783(.A (wr_ptr[1]), .B (n_29), .Y (n_15));
  NOR2XL g6059__3680(.A (n_9), .B (n_19), .Y (n_20));
  AOI22X1 g6078__1617(.A0 (rd_ptr[2]), .A1 (n_9), .B0 (wr_ptr[2]), .B1
       (n_7), .Y (n_8));
  MXI2XL g6077__2802(.A (wr_ptr[3]), .B (n_3), .S0 (rd_ptr[3]), .Y
       (n_6));
  OAI22X1 g6076__1705(.A0 (n_4), .A1 (rd_ptr[1]), .B0 (rd_ptr[0]), .B1
       (n_62), .Y (n_5));
  CLKINVX1 g6084(.A (n_68), .Y (n_64));
  CLKINVX1 g6085(.A (n_29), .Y (n_17));
  NAND2XL g6086__5122(.A (wr_ptr[2]), .B (n_3), .Y (n_31));
  NAND2XL g6087__8246(.A (wr_ptr[3]), .B (n_9), .Y (n_27));
  NAND2XL g6090__7098(.A (rd_ptr[0]), .B (n_7), .Y (n_68));
  NAND2XL g6089__6131(.A (rd_ptr[2]), .B (n_4), .Y (n_67));
  NOR2XL g6079__1881(.A (rd_ptr[4]), .B (wr_ptr[4]), .Y (n_1));
  NAND2XL g6080__5115(.A (wr_ptr[2]), .B (wr_ptr[3]), .Y (n_34));
  NAND2XL g6083__7482(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_70));
  NOR2XL g6088__4733(.A (wr_ptr[2]), .B (wr_ptr[3]), .Y (n_40));
  NOR2XL g6081__6161(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_71));
  NAND2XL g6082__9315(.A (wr_ptr[0]), .B (wr_ptr[1]), .Y (n_19));
  NAND2XL g6091__9945(.A (rst_n), .B (wr_en), .Y (n_29));
  CLKINVX1 g6098(.A (rd_ptr[2]), .Y (n_7));
  CLKINVX1 g6099(.A (rd_ptr[0]), .Y (n_4));
  CLKINVX1 g6092(.A (wr_ptr[0]), .Y (n_16));
  CLKINVX1 g6096(.A (rd_ptr[1]), .Y (n_62));
  INVXL g6095(.A (wr_en), .Y (n_0));
  CLKINVX1 g6094(.A (wr_ptr[3]), .Y (n_3));
  CLKINVX1 g6093(.A (wr_ptr[2]), .Y (n_9));
  BUFX2 drc_bufs6250(.A (n_49), .Y (empty));
  DFFRX1 \wr_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_26), .Q
       (wr_ptr[1]), .QN (n_11));
  NAND2BX1 g2(.AN (n_28), .B (n_40), .Y (n_199));
  NAND2BX1 g6255(.AN (n_30), .B (n_40), .Y (n_200));
  NOR3BX1 g6256(.AN (n_20), .B (wr_ptr[3]), .C (n_29), .Y (n_201));
  NAND3BX1 g6257(.AN (n_19), .B (n_40), .C (n_17), .Y (n_202));
endmodule

