
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 13 2025 15:02:23 IST (Dec 13 2025 09:32:23 UTC)

// Verification Directory fv/fifo 

module fifo(clk, rst_n, wr_en, rd_en, din, dout, empty, full);
  input clk, rst_n, wr_en, rd_en;
  input [7:0] din;
  output [7:0] dout;
  output empty, full;
  wire clk, rst_n, wr_en, rd_en;
  wire [7:0] din;
  wire [7:0] dout;
  wire empty, full;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [4:0] rd_ptr;
  wire [4:0] wr_ptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_18, n_19, n_20, n_21, n_22, n_23, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_52, n_53, n_55, n_56, n_57, n_58, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_190, n_191;
  assign full = 1'b0;
  DFFQX1 \dout_reg[0] (.CK (clk), .D (n_185), .Q (dout[0]));
  DFFQX1 \dout_reg[1] (.CK (clk), .D (n_184), .Q (dout[1]));
  DFFQX1 \dout_reg[3] (.CK (clk), .D (n_178), .Q (dout[3]));
  DFFQX1 \dout_reg[4] (.CK (clk), .D (n_183), .Q (dout[4]));
  DFFQX1 \dout_reg[5] (.CK (clk), .D (n_182), .Q (dout[5]));
  DFFQX1 \dout_reg[2] (.CK (clk), .D (n_181), .Q (dout[2]));
  DFFQX1 \dout_reg[6] (.CK (clk), .D (n_180), .Q (dout[6]));
  DFFQX1 \dout_reg[7] (.CK (clk), .D (n_179), .Q (dout[7]));
  INVXL g5844(.A (n_172), .Y (n_185));
  INVXL g5846(.A (n_177), .Y (n_184));
  INVXL g5845(.A (n_174), .Y (n_183));
  INVXL g5847(.A (n_171), .Y (n_182));
  INVXL g5854(.A (n_173), .Y (n_181));
  INVXL g5853(.A (n_176), .Y (n_180));
  INVXL g5852(.A (n_169), .Y (n_179));
  INVXL g5855(.A (n_170), .Y (n_178));
  AOI211XL g5850__2398(.A0 (\mem[15] [1]), .A1 (n_175), .B0 (n_156),
       .C0 (n_161), .Y (n_177));
  AOI211XL g5857__5107(.A0 (\mem[15] [6]), .A1 (n_175), .B0 (n_168),
       .C0 (n_160), .Y (n_176));
  AOI211XL g5849__6260(.A0 (\mem[15] [4]), .A1 (n_175), .B0 (n_155),
       .C0 (n_162), .Y (n_174));
  AOI211XL g5858__4319(.A0 (\mem[15] [2]), .A1 (n_175), .B0 (n_158),
       .C0 (n_167), .Y (n_173));
  AOI211XL g5848__8428(.A0 (\mem[15] [0]), .A1 (n_175), .B0 (n_157),
       .C0 (n_165), .Y (n_172));
  AOI211XL g5851__5526(.A0 (\mem[15] [5]), .A1 (n_175), .B0 (n_153),
       .C0 (n_166), .Y (n_171));
  AOI211XL g5859__6783(.A0 (\mem[15] [3]), .A1 (n_175), .B0 (n_154),
       .C0 (n_164), .Y (n_170));
  AOI211XL g5856__3680(.A0 (\mem[15] [7]), .A1 (n_175), .B0 (n_159),
       .C0 (n_163), .Y (n_169));
  NAND4XL g5871__1617(.A (n_150), .B (n_147), .C (n_129), .D (n_114),
       .Y (n_168));
  NAND4XL g5869__2802(.A (n_143), .B (n_144), .C (n_140), .D (n_138),
       .Y (n_167));
  NAND4XL g5866__1705(.A (n_120), .B (n_121), .C (n_119), .D (n_141),
       .Y (n_166));
  NAND4XL g5872__5122(.A (n_134), .B (n_142), .C (n_113), .D (n_117),
       .Y (n_165));
  NAND4XL g5861__8246(.A (n_115), .B (n_151), .C (n_128), .D (n_116),
       .Y (n_164));
  NAND4XL g5874__7098(.A (n_152), .B (n_139), .C (n_133), .D (n_135),
       .Y (n_163));
  NAND4XL g5860__6131(.A (n_127), .B (n_130), .C (n_126), .D (n_125),
       .Y (n_162));
  NAND4XL g5863__1881(.A (n_124), .B (n_118), .C (n_123), .D (n_122),
       .Y (n_161));
  NAND4XL g5870__5115(.A (n_79), .B (n_78), .C (n_74), .D (n_76), .Y
       (n_160));
  NAND4XL g5868__7482(.A (n_81), .B (n_105), .C (n_106), .D (n_101), .Y
       (n_159));
  NAND4XL g5867__4733(.A (n_112), .B (n_77), .C (n_80), .D (n_88), .Y
       (n_158));
  NAND4XL g5873__6161(.A (n_91), .B (n_75), .C (n_82), .D (n_87), .Y
       (n_157));
  NAND4XL g5864__9315(.A (n_89), .B (n_107), .C (n_93), .D (n_111), .Y
       (n_156));
  NAND4XL g5862__9945(.A (n_100), .B (n_102), .C (n_97), .D (n_110), .Y
       (n_155));
  NAND4XL g5875__2883(.A (n_94), .B (n_90), .C (n_92), .D (n_73), .Y
       (n_154));
  NAND4XL g5865__2346(.A (n_84), .B (n_85), .C (n_86), .D (n_83), .Y
       (n_153));
  AOI22XL g5944__1666(.A0 (n_146), .A1 (\mem[8] [7]), .B0 (n_145), .B1
       (\mem[7] [7]), .Y (n_152));
  AOI22XL g5890__7410(.A0 (n_149), .A1 (\mem[12] [3]), .B0 (n_148), .B1
       (\mem[11] [3]), .Y (n_151));
  AOI22XL g5928__6417(.A0 (n_149), .A1 (\mem[12] [6]), .B0 (n_148), .B1
       (\mem[11] [6]), .Y (n_150));
  AOI22XL g5929__5477(.A0 (n_146), .A1 (\mem[8] [6]), .B0 (n_145), .B1
       (\mem[7] [6]), .Y (n_147));
  AOI22XL g5930__2398(.A0 (n_146), .A1 (\mem[8] [2]), .B0 (n_145), .B1
       (\mem[7] [2]), .Y (n_144));
  AOI22XL g5931__5107(.A0 (n_149), .A1 (\mem[12] [2]), .B0 (n_148), .B1
       (\mem[11] [2]), .Y (n_143));
  AOI22XL g5932__6260(.A0 (n_146), .A1 (\mem[8] [0]), .B0 (n_145), .B1
       (\mem[7] [0]), .Y (n_142));
  AOI22XL g5933__4319(.A0 (n_137), .A1 (\mem[9] [5]), .B0 (n_136), .B1
       (\mem[10] [5]), .Y (n_141));
  AOI22XL g5934__8428(.A0 (n_132), .A1 (\mem[13] [2]), .B0 (n_131), .B1
       (\mem[14] [2]), .Y (n_140));
  AOI22XL g5938__5526(.A0 (n_149), .A1 (\mem[12] [7]), .B0 (n_148), .B1
       (\mem[11] [7]), .Y (n_139));
  AOI22XL g5939__6783(.A0 (n_137), .A1 (\mem[9] [2]), .B0 (n_136), .B1
       (\mem[10] [2]), .Y (n_138));
  AOI22XL g5940__3680(.A0 (n_137), .A1 (\mem[9] [7]), .B0 (n_136), .B1
       (\mem[10] [7]), .Y (n_135));
  AOI22XL g5941__1617(.A0 (n_149), .A1 (\mem[12] [0]), .B0 (n_148), .B1
       (\mem[11] [0]), .Y (n_134));
  AOI22XL g5942__2802(.A0 (n_132), .A1 (\mem[13] [7]), .B0 (n_131), .B1
       (\mem[14] [7]), .Y (n_133));
  AOI22XL g5898__1705(.A0 (n_149), .A1 (\mem[12] [4]), .B0 (n_148), .B1
       (\mem[11] [4]), .Y (n_130));
  AOI22XL g5927__5122(.A0 (n_137), .A1 (\mem[9] [6]), .B0 (n_136), .B1
       (\mem[10] [6]), .Y (n_129));
  AOI22XL g5889__8246(.A0 (n_132), .A1 (\mem[13] [3]), .B0 (n_131), .B1
       (\mem[14] [3]), .Y (n_128));
  AOI22XL g5900__7098(.A0 (n_146), .A1 (\mem[8] [4]), .B0 (n_145), .B1
       (\mem[7] [4]), .Y (n_127));
  AOI22XL g5902__6131(.A0 (n_132), .A1 (\mem[13] [4]), .B0 (n_131), .B1
       (\mem[14] [4]), .Y (n_126));
  AOI22XL g5903__1881(.A0 (n_137), .A1 (\mem[9] [4]), .B0 (n_136), .B1
       (\mem[10] [4]), .Y (n_125));
  AOI22XL g5905__5115(.A0 (n_149), .A1 (\mem[12] [1]), .B0 (n_148), .B1
       (\mem[11] [1]), .Y (n_124));
  AOI22XL g5907__7482(.A0 (n_132), .A1 (\mem[13] [1]), .B0 (n_131), .B1
       (\mem[14] [1]), .Y (n_123));
  AOI22XL g5909__4733(.A0 (n_137), .A1 (\mem[9] [1]), .B0 (n_136), .B1
       (\mem[10] [1]), .Y (n_122));
  AOI22XL g5912__6161(.A0 (n_146), .A1 (\mem[8] [5]), .B0 (n_145), .B1
       (\mem[7] [5]), .Y (n_121));
  AOI22XL g5914__9315(.A0 (n_149), .A1 (\mem[12] [5]), .B0 (n_148), .B1
       (\mem[11] [5]), .Y (n_120));
  AOI22XL g5915__9945(.A0 (n_132), .A1 (\mem[13] [5]), .B0 (n_131), .B1
       (\mem[14] [5]), .Y (n_119));
  AOI22XL g5885__2883(.A0 (n_146), .A1 (\mem[8] [1]), .B0 (n_145), .B1
       (\mem[7] [1]), .Y (n_118));
  AOI22XL g5919__2346(.A0 (n_132), .A1 (\mem[13] [0]), .B0 (n_131), .B1
       (\mem[14] [0]), .Y (n_117));
  AOI22XL g5886__1666(.A0 (n_137), .A1 (\mem[9] [3]), .B0 (n_136), .B1
       (\mem[10] [3]), .Y (n_116));
  AOI22XL g5887__7410(.A0 (n_146), .A1 (\mem[8] [3]), .B0 (n_145), .B1
       (\mem[7] [3]), .Y (n_115));
  AOI22XL g5925__6417(.A0 (n_132), .A1 (\mem[13] [6]), .B0 (n_131), .B1
       (\mem[14] [6]), .Y (n_114));
  AOI22XL g5945__5477(.A0 (n_137), .A1 (\mem[9] [0]), .B0 (n_136), .B1
       (\mem[10] [0]), .Y (n_113));
  AOI22XL g5901__2398(.A0 (n_99), .A1 (\mem[0] [2]), .B0 (n_98), .B1
       (dout[2]), .Y (n_112));
  AOI22XL g5892__5107(.A0 (n_109), .A1 (\mem[4] [1]), .B0 (n_108), .B1
       (\mem[3] [1]), .Y (n_111));
  AOI22XL g5893__6260(.A0 (n_109), .A1 (\mem[4] [4]), .B0 (n_108), .B1
       (\mem[3] [4]), .Y (n_110));
  AOI22XL g5894__4319(.A0 (n_104), .A1 (\mem[5] [1]), .B0 (n_103), .B1
       (\mem[6] [1]), .Y (n_107));
  AOI22XL g5935__8428(.A0 (n_96), .A1 (\mem[1] [7]), .B0 (n_95), .B1
       (\mem[2] [7]), .Y (n_106));
  AOI22XL g5936__5526(.A0 (n_104), .A1 (\mem[5] [7]), .B0 (n_103), .B1
       (\mem[6] [7]), .Y (n_105));
  AOI22XL g5895__6783(.A0 (n_104), .A1 (\mem[5] [4]), .B0 (n_103), .B1
       (\mem[6] [4]), .Y (n_102));
  AOI22XL g5937__3680(.A0 (n_109), .A1 (\mem[4] [7]), .B0 (n_108), .B1
       (\mem[3] [7]), .Y (n_101));
  AOI22XL g5896__1617(.A0 (n_99), .A1 (\mem[0] [4]), .B0 (n_98), .B1
       (dout[4]), .Y (n_100));
  AOI22XL g5897__2802(.A0 (n_96), .A1 (\mem[1] [4]), .B0 (n_95), .B1
       (\mem[2] [4]), .Y (n_97));
  AOI22XL g5943__1705(.A0 (n_99), .A1 (\mem[0] [3]), .B0 (n_98), .B1
       (dout[3]), .Y (n_94));
  AOI22XL g5899__5122(.A0 (n_96), .A1 (\mem[1] [1]), .B0 (n_95), .B1
       (\mem[2] [1]), .Y (n_93));
  AOI22XL g5946__8246(.A0 (n_96), .A1 (\mem[1] [3]), .B0 (n_95), .B1
       (\mem[2] [3]), .Y (n_92));
  AOI22XL g5947__7098(.A0 (n_99), .A1 (\mem[0] [0]), .B0 (n_98), .B1
       (dout[0]), .Y (n_91));
  AOI22XL g5948__6131(.A0 (n_104), .A1 (\mem[5] [3]), .B0 (n_103), .B1
       (\mem[6] [3]), .Y (n_90));
  AOI22XL g5891__1881(.A0 (n_99), .A1 (\mem[0] [1]), .B0 (n_98), .B1
       (dout[1]), .Y (n_89));
  AOI22XL g5926__5115(.A0 (n_109), .A1 (\mem[4] [2]), .B0 (n_108), .B1
       (\mem[3] [2]), .Y (n_88));
  AOI22XL g5904__7482(.A0 (n_109), .A1 (\mem[4] [0]), .B0 (n_108), .B1
       (\mem[3] [0]), .Y (n_87));
  AOI22XL g5906__4733(.A0 (n_96), .A1 (\mem[1] [5]), .B0 (n_95), .B1
       (\mem[2] [5]), .Y (n_86));
  AOI22XL g5908__6161(.A0 (n_104), .A1 (\mem[5] [5]), .B0 (n_103), .B1
       (\mem[6] [5]), .Y (n_85));
  AOI22XL g5910__9315(.A0 (n_99), .A1 (\mem[0] [5]), .B0 (n_98), .B1
       (dout[5]), .Y (n_84));
  AOI22XL g5911__9945(.A0 (n_109), .A1 (\mem[4] [5]), .B0 (n_108), .B1
       (\mem[3] [5]), .Y (n_83));
  AOI22XL g5913__2883(.A0 (n_96), .A1 (\mem[1] [0]), .B0 (n_95), .B1
       (\mem[2] [0]), .Y (n_82));
  AOI22XL g5917__2346(.A0 (n_99), .A1 (\mem[0] [7]), .B0 (n_98), .B1
       (dout[7]), .Y (n_81));
  AOI22XL g5918__1666(.A0 (n_96), .A1 (\mem[1] [2]), .B0 (n_95), .B1
       (\mem[2] [2]), .Y (n_80));
  AOI22XL g5920__7410(.A0 (n_99), .A1 (\mem[0] [6]), .B0 (n_98), .B1
       (dout[6]), .Y (n_79));
  AOI22XL g5921__6417(.A0 (n_104), .A1 (\mem[5] [6]), .B0 (n_103), .B1
       (\mem[6] [6]), .Y (n_78));
  AOI22XL g5922__5477(.A0 (n_104), .A1 (\mem[5] [2]), .B0 (n_103), .B1
       (\mem[6] [2]), .Y (n_77));
  AOI22XL g5923__2398(.A0 (n_109), .A1 (\mem[4] [6]), .B0 (n_108), .B1
       (\mem[3] [6]), .Y (n_76));
  AOI22XL g5888__5107(.A0 (n_104), .A1 (\mem[5] [0]), .B0 (n_103), .B1
       (\mem[6] [0]), .Y (n_75));
  AOI22XL g5924__6260(.A0 (n_96), .A1 (\mem[1] [6]), .B0 (n_95), .B1
       (\mem[2] [6]), .Y (n_74));
  AOI22XL g5949__4319(.A0 (n_109), .A1 (\mem[4] [3]), .B0 (n_108), .B1
       (\mem[3] [3]), .Y (n_73));
  NOR2BX1 g5965__8428(.AN (n_71), .B (n_72), .Y (n_136));
  NOR2XL g5964__5526(.A (n_70), .B (n_72), .Y (n_175));
  NOR2BX1 g5961__6783(.AN (n_71), .B (n_69), .Y (n_146));
  NOR2XL g5970__3680(.A (n_70), .B (n_69), .Y (n_132));
  NOR2XL g5975__1617(.A (n_68), .B (n_69), .Y (n_137));
  NOR2XL g5974__2802(.A (n_68), .B (n_72), .Y (n_148));
  NOR2XL g5973__1705(.A (n_67), .B (n_72), .Y (n_131));
  NOR2XL g5980__5122(.A (n_67), .B (n_69), .Y (n_149));
  NOR2BX1 g5971__8246(.AN (n_66), .B (n_70), .Y (n_104));
  AND2X1 g5966__7098(.A (n_71), .B (n_65), .Y (n_95));
  AND2X1 g5963__6131(.A (n_71), .B (n_66), .Y (n_99));
  NOR2BX1 g5972__1881(.AN (n_66), .B (n_67), .Y (n_109));
  AND2X1 g5978__5115(.A (n_64), .B (n_65), .Y (n_108));
  NOR2BX1 g5977__7482(.AN (n_65), .B (n_70), .Y (n_145));
  AND2X1 g5976__4733(.A (n_64), .B (n_66), .Y (n_96));
  NOR2BX1 g5979__6161(.AN (n_65), .B (n_67), .Y (n_103));
  NAND3X1 g5984__9315(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_63), .Y
       (n_72));
  NAND3X1 g5986__9945(.A (rd_ptr[3]), .B (n_62), .C (n_63), .Y (n_69));
  NOR3X1 g5982__2883(.A (rd_ptr[3]), .B (rd_ptr[1]), .C (n_98), .Y
       (n_66));
  NOR3X1 g5985__2346(.A (rd_ptr[3]), .B (n_62), .C (n_98), .Y (n_65));
  SDFFRHQX1 \rd_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (n_60), .SI
       (n_61), .SE (rd_ptr[0]), .Q (rd_ptr[0]));
  CLKINVX1 g5996(.A (n_98), .Y (n_63));
  SDFFRHQX1 \rd_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (n_32), .SI
       (rd_ptr[3]), .SE (n_61), .Q (rd_ptr[3]));
  SDFFRHQX1 \rd_ptr_reg[4] (.RN (rst_n), .CK (clk), .D (n_42), .SI
       (rd_ptr[4]), .SE (n_61), .Q (rd_ptr[4]));
  SDFFRHQX1 \rd_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (n_25), .SI
       (rd_ptr[2]), .SE (n_61), .Q (rd_ptr[2]));
  SDFFRHQX1 \rd_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_8), .SI
       (rd_ptr[1]), .SE (n_61), .Q (rd_ptr[1]));
  NAND2XL g6005__1666(.A (rst_n), .B (n_60), .Y (n_98));
  SDFFRHQX1 \wr_ptr_reg[4] (.RN (rst_n), .CK (clk), .D (wr_ptr[4]), .SI
       (n_45), .SE (wr_en), .Q (wr_ptr[4]));
  SDFFQX1 \mem_reg[0][2] (.CK (clk), .D (din[2]), .SI (\mem[0] [2]),
       .SE (n_190), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[0][7] (.CK (clk), .D (din[7]), .SI (\mem[0] [7]),
       .SE (n_190), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[0][3] (.CK (clk), .D (din[3]), .SI (\mem[0] [3]),
       .SE (n_190), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][6] (.CK (clk), .D (din[6]), .SI (\mem[0] [6]),
       .SE (n_190), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][1] (.CK (clk), .D (din[1]), .SI (\mem[0] [1]),
       .SE (n_190), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][0] (.CK (clk), .D (din[0]), .SI (\mem[0] [0]),
       .SE (n_190), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][4] (.CK (clk), .D (din[4]), .SI (\mem[0] [4]),
       .SE (n_190), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][5] (.CK (clk), .D (din[5]), .SI (\mem[0] [5]),
       .SE (n_190), .Q (\mem[0] [5]));
  CLKINVX1 g6056(.A (n_61), .Y (n_60));
  SDFFQX1 \mem_reg[4][5] (.CK (clk), .D (\mem[4] [5]), .SI (din[5]),
       .SE (n_57), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[8][5] (.CK (clk), .D (\mem[8] [5]), .SI (din[5]),
       .SE (n_58), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (clk), .D (\mem[8] [6]), .SI (din[6]),
       .SE (n_58), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[8][4] (.CK (clk), .D (\mem[8] [4]), .SI (din[4]),
       .SE (n_58), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[1][6] (.CK (clk), .D (\mem[1] [6]), .SI (din[6]),
       .SE (n_52), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[5][6] (.CK (clk), .D (\mem[5] [6]), .SI (din[6]),
       .SE (n_56), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[4][3] (.CK (clk), .D (\mem[4] [3]), .SI (din[3]),
       .SE (n_57), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[5][3] (.CK (clk), .D (\mem[5] [3]), .SI (din[3]),
       .SE (n_56), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[13][5] (.CK (clk), .D (\mem[13] [5]), .SI (din[5]),
       .SE (n_53), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[9][5] (.CK (clk), .D (\mem[9] [5]), .SI (din[5]),
       .SE (n_50), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[4][7] (.CK (clk), .D (\mem[4] [7]), .SI (din[7]),
       .SE (n_57), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[7][6] (.CK (clk), .D (\mem[7] [6]), .SI (din[6]),
       .SE (n_191), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[15][1] (.CK (clk), .D (\mem[15] [1]), .SI (din[1]),
       .SE (n_55), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][0] (.CK (clk), .D (\mem[15] [0]), .SI (din[0]),
       .SE (n_55), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][7] (.CK (clk), .D (\mem[15] [7]), .SI (din[7]),
       .SE (n_55), .Q (\mem[15] [7]));
  SDFFQX1 \mem_reg[15][2] (.CK (clk), .D (\mem[15] [2]), .SI (din[2]),
       .SE (n_55), .Q (\mem[15] [2]));
  SDFFQX1 \mem_reg[15][4] (.CK (clk), .D (\mem[15] [4]), .SI (din[4]),
       .SE (n_55), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][3] (.CK (clk), .D (\mem[15] [3]), .SI (din[3]),
       .SE (n_55), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][6] (.CK (clk), .D (\mem[15] [6]), .SI (din[6]),
       .SE (n_55), .Q (\mem[15] [6]));
  SDFFQX1 \mem_reg[7][3] (.CK (clk), .D (\mem[7] [3]), .SI (din[3]),
       .SE (n_191), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][2] (.CK (clk), .D (\mem[7] [2]), .SI (din[2]),
       .SE (n_191), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][1] (.CK (clk), .D (\mem[7] [1]), .SI (din[1]),
       .SE (n_191), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][0] (.CK (clk), .D (\mem[7] [0]), .SI (din[0]),
       .SE (n_191), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][5] (.CK (clk), .D (\mem[7] [5]), .SI (din[5]),
       .SE (n_191), .Q (\mem[7] [5]));
  SDFFQX1 \mem_reg[7][4] (.CK (clk), .D (\mem[7] [4]), .SI (din[4]),
       .SE (n_191), .Q (\mem[7] [4]));
  SDFFQX1 \mem_reg[7][7] (.CK (clk), .D (\mem[7] [7]), .SI (din[7]),
       .SE (n_191), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[13][3] (.CK (clk), .D (\mem[13] [3]), .SI (din[3]),
       .SE (n_53), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[1][2] (.CK (clk), .D (\mem[1] [2]), .SI (din[2]),
       .SE (n_52), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[1][3] (.CK (clk), .D (\mem[1] [3]), .SI (din[3]),
       .SE (n_52), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[1][4] (.CK (clk), .D (\mem[1] [4]), .SI (din[4]),
       .SE (n_52), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[1][7] (.CK (clk), .D (\mem[1] [7]), .SI (din[7]),
       .SE (n_52), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[1][0] (.CK (clk), .D (\mem[1] [0]), .SI (din[0]),
       .SE (n_52), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[4][0] (.CK (clk), .D (\mem[4] [0]), .SI (din[0]),
       .SE (n_57), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (clk), .D (\mem[4] [1]), .SI (din[1]),
       .SE (n_57), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (clk), .D (\mem[4] [2]), .SI (din[2]),
       .SE (n_57), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][4] (.CK (clk), .D (\mem[4] [4]), .SI (din[4]),
       .SE (n_57), .Q (\mem[4] [4]));
  NAND2BX1 g6106__7410(.AN (empty), .B (rd_en), .Y (n_61));
  SDFFQX1 \mem_reg[13][1] (.CK (clk), .D (\mem[13] [1]), .SI (din[1]),
       .SE (n_53), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[5][0] (.CK (clk), .D (\mem[5] [0]), .SI (din[0]),
       .SE (n_56), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (clk), .D (\mem[5] [1]), .SI (din[1]),
       .SE (n_56), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[5][2] (.CK (clk), .D (\mem[5] [2]), .SI (din[2]),
       .SE (n_56), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[5][4] (.CK (clk), .D (\mem[5] [4]), .SI (din[4]),
       .SE (n_56), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (clk), .D (\mem[5] [5]), .SI (din[5]),
       .SE (n_56), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][7] (.CK (clk), .D (\mem[5] [7]), .SI (din[7]),
       .SE (n_56), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[8][0] (.CK (clk), .D (\mem[8] [0]), .SI (din[0]),
       .SE (n_58), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][1] (.CK (clk), .D (\mem[8] [1]), .SI (din[1]),
       .SE (n_58), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[1][5] (.CK (clk), .D (\mem[1] [5]), .SI (din[5]),
       .SE (n_52), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[8][3] (.CK (clk), .D (\mem[8] [3]), .SI (din[3]),
       .SE (n_58), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][2] (.CK (clk), .D (\mem[8] [2]), .SI (din[2]),
       .SE (n_58), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[8][7] (.CK (clk), .D (\mem[8] [7]), .SI (din[7]),
       .SE (n_58), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[9][0] (.CK (clk), .D (\mem[9] [0]), .SI (din[0]),
       .SE (n_50), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (clk), .D (\mem[9] [1]), .SI (din[1]),
       .SE (n_50), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][2] (.CK (clk), .D (\mem[9] [2]), .SI (din[2]),
       .SE (n_50), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[9][3] (.CK (clk), .D (\mem[9] [3]), .SI (din[3]),
       .SE (n_50), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[1][1] (.CK (clk), .D (\mem[1] [1]), .SI (din[1]),
       .SE (n_52), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[9][4] (.CK (clk), .D (\mem[9] [4]), .SI (din[4]),
       .SE (n_50), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][6] (.CK (clk), .D (\mem[9] [6]), .SI (din[6]),
       .SE (n_50), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[9][7] (.CK (clk), .D (\mem[9] [7]), .SI (din[7]),
       .SE (n_50), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[12][0] (.CK (clk), .D (\mem[12] [0]), .SI (din[0]),
       .SE (n_49), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (clk), .D (\mem[12] [1]), .SI (din[1]),
       .SE (n_49), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (clk), .D (\mem[12] [2]), .SI (din[2]),
       .SE (n_49), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (clk), .D (\mem[12] [3]), .SI (din[3]),
       .SE (n_49), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (clk), .D (\mem[12] [4]), .SI (din[4]),
       .SE (n_49), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][6] (.CK (clk), .D (\mem[12] [6]), .SI (din[6]),
       .SE (n_49), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[12][7] (.CK (clk), .D (\mem[12] [7]), .SI (din[7]),
       .SE (n_49), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[13][0] (.CK (clk), .D (\mem[13] [0]), .SI (din[0]),
       .SE (n_53), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][2] (.CK (clk), .D (\mem[13] [2]), .SI (din[2]),
       .SE (n_53), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][4] (.CK (clk), .D (\mem[13] [4]), .SI (din[4]),
       .SE (n_53), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[13][6] (.CK (clk), .D (\mem[13] [6]), .SI (din[6]),
       .SE (n_53), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (clk), .D (\mem[13] [7]), .SI (din[7]),
       .SE (n_53), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[12][5] (.CK (clk), .D (\mem[12] [5]), .SI (din[5]),
       .SE (n_49), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[15][5] (.CK (clk), .D (\mem[15] [5]), .SI (din[5]),
       .SE (n_55), .Q (\mem[15] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (clk), .D (\mem[4] [6]), .SI (din[6]),
       .SE (n_57), .Q (\mem[4] [6]));
  SDFFRHQX1 \wr_ptr_reg[3] (.RN (rst_n), .CK (clk), .D (wr_ptr[3]), .SI
       (n_33), .SE (wr_en), .Q (wr_ptr[3]));
  SDFFQX1 \mem_reg[6][0] (.CK (clk), .D (din[0]), .SI (\mem[6] [0]),
       .SE (n_48), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][7] (.CK (clk), .D (din[7]), .SI (\mem[6] [7]),
       .SE (n_48), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[14][5] (.CK (clk), .D (\mem[14] [5]), .SI (din[5]),
       .SE (n_47), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (clk), .D (din[6]), .SI (\mem[6] [6]),
       .SE (n_48), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[14][3] (.CK (clk), .D (\mem[14] [3]), .SI (din[3]),
       .SE (n_47), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][6] (.CK (clk), .D (\mem[14] [6]), .SI (din[6]),
       .SE (n_47), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[10][5] (.CK (clk), .D (din[5]), .SI (\mem[10] [5]),
       .SE (n_46), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[6][1] (.CK (clk), .D (din[1]), .SI (\mem[6] [1]),
       .SE (n_48), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][3] (.CK (clk), .D (din[3]), .SI (\mem[6] [3]),
       .SE (n_48), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (clk), .D (din[4]), .SI (\mem[6] [4]),
       .SE (n_48), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (clk), .D (din[5]), .SI (\mem[6] [5]),
       .SE (n_48), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[10][0] (.CK (clk), .D (din[0]), .SI (\mem[10] [0]),
       .SE (n_46), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[10][7] (.CK (clk), .D (din[7]), .SI (\mem[10] [7]),
       .SE (n_46), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[10][3] (.CK (clk), .D (din[3]), .SI (\mem[10] [3]),
       .SE (n_46), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][4] (.CK (clk), .D (din[4]), .SI (\mem[10] [4]),
       .SE (n_46), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[10][6] (.CK (clk), .D (din[6]), .SI (\mem[10] [6]),
       .SE (n_46), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[14][0] (.CK (clk), .D (\mem[14] [0]), .SI (din[0]),
       .SE (n_47), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[14][4] (.CK (clk), .D (\mem[14] [4]), .SI (din[4]),
       .SE (n_47), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[10][2] (.CK (clk), .D (din[2]), .SI (\mem[10] [2]),
       .SE (n_46), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[14][7] (.CK (clk), .D (\mem[14] [7]), .SI (din[7]),
       .SE (n_47), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[6][2] (.CK (clk), .D (din[2]), .SI (\mem[6] [2]),
       .SE (n_48), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[14][1] (.CK (clk), .D (\mem[14] [1]), .SI (din[1]),
       .SE (n_47), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][2] (.CK (clk), .D (\mem[14] [2]), .SI (din[2]),
       .SE (n_47), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[10][1] (.CK (clk), .D (din[1]), .SI (\mem[10] [1]),
       .SE (n_46), .Q (\mem[10] [1]));
  OAI21X1 g5954__6417(.A0 (wr_ptr[4]), .A1 (n_34), .B0 (n_35), .Y
       (n_45));
  SDFFQX1 \mem_reg[2][2] (.CK (clk), .D (din[2]), .SI (\mem[2] [2]),
       .SE (n_41), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[11][7] (.CK (clk), .D (\mem[11] [7]), .SI (din[7]),
       .SE (n_44), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[3][3] (.CK (clk), .D (din[3]), .SI (\mem[3] [3]),
       .SE (n_43), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[11][1] (.CK (clk), .D (\mem[11] [1]), .SI (din[1]),
       .SE (n_44), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[11][4] (.CK (clk), .D (\mem[11] [4]), .SI (din[4]),
       .SE (n_44), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[11][6] (.CK (clk), .D (\mem[11] [6]), .SI (din[6]),
       .SE (n_44), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[11][2] (.CK (clk), .D (\mem[11] [2]), .SI (din[2]),
       .SE (n_44), .Q (\mem[11] [2]));
  NOR3X1 g6110__5477(.A (n_11), .B (n_15), .C (n_26), .Y (empty));
  SDFFQX1 \mem_reg[3][5] (.CK (clk), .D (din[5]), .SI (\mem[3] [5]),
       .SE (n_43), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[3][1] (.CK (clk), .D (din[1]), .SI (\mem[3] [1]),
       .SE (n_43), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[11][0] (.CK (clk), .D (\mem[11] [0]), .SI (din[0]),
       .SE (n_44), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[3][2] (.CK (clk), .D (din[2]), .SI (\mem[3] [2]),
       .SE (n_43), .Q (\mem[3] [2]));
  SDFFRHQX1 \wr_ptr_reg[2] (.RN (rst_n), .CK (clk), .D (wr_ptr[2]), .SI
       (n_22), .SE (wr_en), .Q (wr_ptr[2]));
  OAI21X1 g6057__2398(.A0 (rd_ptr[4]), .A1 (n_39), .B0 (n_40), .Y
       (n_42));
  SDFFQX1 \mem_reg[3][7] (.CK (clk), .D (din[7]), .SI (\mem[3] [7]),
       .SE (n_43), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[3][0] (.CK (clk), .D (din[0]), .SI (\mem[3] [0]),
       .SE (n_43), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[11][3] (.CK (clk), .D (\mem[11] [3]), .SI (din[3]),
       .SE (n_44), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[11][5] (.CK (clk), .D (\mem[11] [5]), .SI (din[5]),
       .SE (n_44), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[2][7] (.CK (clk), .D (din[7]), .SI (\mem[2] [7]),
       .SE (n_41), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[2][0] (.CK (clk), .D (din[0]), .SI (\mem[2] [0]),
       .SE (n_41), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (clk), .D (din[1]), .SI (\mem[2] [1]),
       .SE (n_41), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][3] (.CK (clk), .D (din[3]), .SI (\mem[2] [3]),
       .SE (n_41), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][4] (.CK (clk), .D (din[4]), .SI (\mem[2] [4]),
       .SE (n_41), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (clk), .D (din[5]), .SI (\mem[2] [5]),
       .SE (n_41), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (clk), .D (din[6]), .SI (\mem[2] [6]),
       .SE (n_41), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[3][4] (.CK (clk), .D (din[4]), .SI (\mem[3] [4]),
       .SE (n_43), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][6] (.CK (clk), .D (din[6]), .SI (\mem[3] [6]),
       .SE (n_43), .Q (\mem[3] [6]));
  NAND2XL g6109__6260(.A (rd_ptr[4]), .B (n_39), .Y (n_40));
  NOR2XL g6115__8428(.A (n_38), .B (n_29), .Y (n_49));
  NOR2XL g6117__5526(.A (n_28), .B (n_37), .Y (n_56));
  NOR2XL g6118__6783(.A (n_38), .B (n_37), .Y (n_53));
  NOR2BX1 g6119__3680(.AN (n_36), .B (n_37), .Y (n_52));
  NAND2XL g5959__1617(.A (wr_ptr[4]), .B (n_34), .Y (n_35));
  OA21XL g5997__2802(.A0 (wr_ptr[3]), .A1 (n_21), .B0 (n_34), .Y
       (n_33));
  OA21XL g6126__1705(.A0 (rd_ptr[3]), .A1 (n_19), .B0 (n_39), .Y
       (n_32));
  NOR2XL g6120__5122(.A (n_30), .B (n_37), .Y (n_50));
  NOR2XL g5981__8246(.A (n_31), .B (n_34), .Y (n_55));
  NOR2XL g6131__7098(.A (n_30), .B (n_29), .Y (n_58));
  NOR2XL g6130__6131(.A (n_28), .B (n_29), .Y (n_57));
  OAI21XL g6111__1881(.A0 (wr_en), .A1 (n_14), .B0 (n_16), .Y (n_27));
  OAI211X1 g6123__5115(.A0 (wr_ptr[1]), .A1 (n_62), .B0 (n_6), .C0
       (n_9), .Y (n_26));
  NOR2XL g6121__7482(.A (n_38), .B (n_23), .Y (n_47));
  OAI221X1 g6124__4733(.A0 (n_62), .A1 (n_68), .B0 (n_5), .B1
       (rd_ptr[1]), .C0 (n_67), .Y (n_25));
  OR2X1 g6129__6161(.A (n_28), .B (n_23), .Y (n_48));
  OR2X1 g6128__9315(.A (n_30), .B (n_23), .Y (n_46));
  AOI21X1 g6113__9945(.A0 (n_10), .A1 (n_20), .B0 (n_21), .Y (n_22));
  NAND2XL g6105__2883(.A (wr_ptr[3]), .B (n_21), .Y (n_34));
  NOR3X1 g6112__2346(.A (n_31), .B (n_20), .C (n_30), .Y (n_44));
  NAND3X1 g6114__1666(.A (n_3), .B (n_4), .C (n_36), .Y (n_43));
  NAND2XL g6139__7410(.A (rd_ptr[3]), .B (n_19), .Y (n_39));
  NAND2XL g6134__6417(.A (wr_ptr[0]), .B (n_18), .Y (n_37));
  NAND2XL g6135__5477(.A (n_13), .B (n_18), .Y (n_29));
  NAND2XL g6116__2398(.A (n_36), .B (n_12), .Y (n_41));
  SDFFRHQX1 \wr_ptr_reg[0] (.RN (rst_n), .CK (clk), .D (wr_en), .SI
       (n_0), .SE (wr_ptr[0]), .Q (wr_ptr[0]));
  OAI211XL g6125__5107(.A0 (wr_ptr[0]), .A1 (wr_ptr[1]), .B0 (wr_en),
       .C0 (n_20), .Y (n_16));
  OAI222XL g6138__6260(.A0 (rd_ptr[1]), .A1 (n_14), .B0 (wr_ptr[0]),
       .B1 (n_7), .C0 (n_13), .C1 (rd_ptr[0]), .Y (n_15));
  CLKINVX1 g6137(.A (n_12), .Y (n_23));
  AOI21X1 g6141__4319(.A0 (rd_ptr[4]), .A1 (wr_ptr[4]), .B0 (n_1), .Y
       (n_11));
  NOR2XL g6142__8428(.A (n_62), .B (n_70), .Y (n_19));
  NOR3X1 g6140__5526(.A (n_31), .B (wr_ptr[0]), .C (n_14), .Y (n_12));
  NOR2XL g6127__6783(.A (n_10), .B (n_20), .Y (n_21));
  MXI2XL g6145__3680(.A (wr_ptr[3]), .B (n_2), .S0 (rd_ptr[3]), .Y
       (n_9));
  OAI22X1 g6144__1617(.A0 (n_7), .A1 (rd_ptr[1]), .B0 (rd_ptr[0]), .B1
       (n_62), .Y (n_8));
  AOI22X1 g6146__2802(.A0 (rd_ptr[2]), .A1 (n_10), .B0 (wr_ptr[2]), .B1
       (n_5), .Y (n_6));
  CLKINVX1 g6152(.A (n_68), .Y (n_64));
  NOR2XL g6143__1705(.A (n_31), .B (wr_ptr[1]), .Y (n_18));
  INVXL g6132(.A (n_20), .Y (n_4));
  INVXL g6153(.A (n_31), .Y (n_3));
  NAND2XL g6154__5122(.A (wr_ptr[2]), .B (n_2), .Y (n_28));
  NAND2XL g6155__8246(.A (wr_ptr[3]), .B (n_10), .Y (n_30));
  NAND2XL g6157__7098(.A (rd_ptr[0]), .B (n_5), .Y (n_68));
  NAND2XL g6158__6131(.A (rd_ptr[2]), .B (n_7), .Y (n_67));
  NOR2XL g6147__1881(.A (rd_ptr[4]), .B (wr_ptr[4]), .Y (n_1));
  NAND2XL g6148__5115(.A (wr_ptr[2]), .B (wr_ptr[3]), .Y (n_38));
  NAND2XL g6151__7482(.A (wr_ptr[0]), .B (wr_ptr[1]), .Y (n_20));
  NOR2XL g6156__4733(.A (wr_ptr[2]), .B (wr_ptr[3]), .Y (n_36));
  NOR2XL g6149__6161(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_71));
  NAND2XL g6150__9315(.A (rd_ptr[0]), .B (rd_ptr[2]), .Y (n_70));
  NAND2XL g6159__9945(.A (wr_en), .B (rst_n), .Y (n_31));
  INVXL g6163(.A (wr_en), .Y (n_0));
  CLKINVX1 g6165(.A (rd_ptr[0]), .Y (n_7));
  CLKINVX1 g6161(.A (rd_ptr[2]), .Y (n_5));
  CLKINVX1 g6167(.A (rd_ptr[1]), .Y (n_62));
  CLKINVX1 g6166(.A (wr_ptr[3]), .Y (n_2));
  CLKINVX1 g6162(.A (wr_ptr[0]), .Y (n_13));
  CLKINVX1 g6164(.A (wr_ptr[2]), .Y (n_10));
  DFFRX1 \wr_ptr_reg[1] (.RN (rst_n), .CK (clk), .D (n_27), .Q
       (wr_ptr[1]), .QN (n_14));
  NAND2BX1 g2(.AN (n_29), .B (n_36), .Y (n_190));
  NOR3BX1 g6316(.AN (n_21), .B (n_31), .C (wr_ptr[3]), .Y (n_191));
endmodule

